{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_status_global{name=\"handler_commit\"}[2m]) / 2 ",
     "legendFormat": "Commit"
    },
    {
     "expr": "idelta(mysql_status_global{name=\"handler_rollback\"}[2m]) / 2",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_status_global{name=\"questions\"}[2m]) ",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Top File ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_perf_schema_file_summary_instances_count_star[2m]) > 0",
     "legendFormat": "{{file_name}}"
    },
    {
     "expr": "idelta(mysql_perf_schema_file_summary_instances_read_bytes[2m]) > 0",
     "legendFormat": "{{file_name}}"
    },
    {
     "expr": "idelta(mysql_perf_schema_file_summary_instances_write_bytes [2m]) > 0",
     "legendFormat": "{{file_name}}"
    }
   ]
  },
  {
   "title": "DML",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_status_global{name=\"com_insert\"}[2m])",
     "legendFormat": "Insert"
    },
    {
     "expr": "idelta(mysql_status_global{name=\"com_update\"}[2m])",
     "legendFormat": "Update"
    },
    {
     "expr": "idelta(mysql_status_global{name=\"com_delete\"}[2m])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "innodb_buffer_pool_reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_status_global{name=\"innodb_buffer_pool_reads\"}[2m])",
     "legendFormat": "reads"
    },
    {
     "expr": "idelta(mysql_status_global{name=\"innodb_buffer_pool_read_requests\"}[2m])",
     "legendFormat": "read requests"
    }
   ]
  },
  {
   "title": "SQL Wait Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(mysql_perf_schema_events_statements_count_star_total[2m]) / idelta(mysql_perf_schema_events_statements_timer_wait_total[2m]))"
    }
   ]
  },
  {
   "title": "dirty buffer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mysql_status_global{name=\"innodb_buffer_pool_bytes_dirty\"}"
    }
   ]
  }
 ]
}