apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: mysql-exporter
  name: mysql-exporter1
  namespace: monitoring
spec:
  ports:
    - name: https
      port: 9104
      protocol: TCP
      targetPort: https
  selector:
    app: mysql-exporter1
