name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.4"
      - run: ls -l ./
      - run: pwd
      - run: go build -o mysqld_exporter
        env:
          GOBIN: /home/runner/go/bin
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: shinhwagk/mysqld_exporter:0.0.2
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
